### ISSUE TITLE
Docker-compose up command 

### ISSUE THREAD

**Issue by Abhishek-IOT** [sympy/sympy-live#181] opened 2021-01-14 16:46 UTC
It is showing file is missing although I have used the same procedure to clone the repository.
![dockernot](https://user-images.githubusercontent.com/53862677/104621246-e66e7500-56b5-11eb-81db-c7376666f945.png)

**Comment by ivanistheone** [comment] 2021-01-14 17:24
the `\r` tells me something special not right is happening to line endings (UNIX vs Windows).

Consider adding a  `dos2unix` step to the Dockerfile or using UNIX line endings for the git project, see section "Cloning Git Projects With Unix Line Endings"  https://willi.am/blog/2016/08/11/docker-for-windows-dealing-with-windows-line-endings/

**Comment by Abhishek-IOT** [comment] 2021-01-15 05:15
@ivanistheone I Cloned the repository like this..."git clone https://github.com/Abhishek-IOT/sympy-live.git --config core.autocrlf=input"...But it is still giving the same error when docker-compose up command is used.

**Comment by ivanistheone** [comment] 2021-01-15 14:30
Sorry don't have a WIN machine to test right now, but wondering after checking out the new repo, **did you do `docker build` again?**  If you didn't see this [build step](https://github.com/sympy/sympy-live/blob/master/docker/app/Dockerfile#L13) happen a new, you might still have the old docker image.

Here are some more things you could try:

1. `docker-compose build --no-cache`   before docker `docker-compose up`

2.  play around with your text editor and try to change the line ending of the file run.sh (if the special git checkout didn't work you can fix manually for the two scripts: https://github.com/sympy/sympy-live/blob/master/docker/app/run.sh and https://github.com/sympy/sympy-live/blob/master/docker/datastore/run.sh )

3. try playing with .gitattributes as descr in this blog post https://techblog.dorogin.com/case-of-windows-line-ending-in-bash-script-7236f056abe

**Comment by Abhishek-IOT** [comment] 2021-01-16 03:33
Actually the docker-compose up command only makes the build of the docker image but... you are right it seems that the old image is showing this time also.

**Comment by Abhishek-IOT** [comment] 2021-01-16 03:34
@ can you tell me what git command I should use to clone the repository with unix ending for sympy.....I think I have done it correct but just wanted to make sure.

**Comment by ivanistheone** [comment] 2021-01-16 03:55
According to  https://stackoverflow.com/a/13154031/127114 this should work:

1. Delete the old repo closes/checkouts

2. In a new terminal, set your git global settings
```bash
git config --global core.autocrlf false
```
to disable git trying to be smart.

3. Git clone as usual (no special arguments)
then re-build with --no-cache and try again



You can check your git global configus using `git config --global --list`

for context
 - cr = carriage return = `\r`
 - lf = line feed = `\n`

on UNIX, each line of a file ends with `\n`, while  
on windows, each line of a file ends with `\r\n`  (e.g in notepad)

in general it shouldn't be a problem if you work on your code using the UNIX conventions (`lf` only) --- just use a text editor that is specialized for code


if steps 1--3 above don't work; please post a) what you see when you type `git config --global --list` and b) also let me know which git are you using, sygwin, msysgit, WSL, chocolatey, etc. (since there are multiple ways to get git on windows)

**Comment by Abhishek-IOT** [comment] 2021-01-21 16:10
@ivanistheone  Thanks for the support buddy.
Steps done by me were=
1)Deleted my old repository
2)Deleted the old docker image that was created 
3)Set this as git config --global core.autocrlf false
4)Then clone the repository as it is.
5)Build the docker image with :docker-compose build --no-cache
6)Then ran the command docker-compose up it worked.

**Comment by Abhishek-IOT** [comment] 2021-01-21 16:14
when I ran the docker-compose up command when I copy and paste the http://0.0.0.0:8080 for accessing the default or when copy and paste http://0.0.0.0:8083 for admin server.....It is showing this in browser="This site can’t be reachedThe webpage at http://0.0.0.0:8080/ might be temporarily down or it may have moved permanently to a new web address."

**Comment by ivanistheone** [comment] 2021-01-21 16:40
Hm... I haven't run the docker setup recently [was too big download and running low on disk space right now] so not sure if this is expected behaviour.

Maybe  @aktech   could point you to further dev setup instructions or other config necessary?

**Comment by aktech** [comment] 2021-01-21 20:20
@Abhishek-IOT It seems the `pkg_resource` import is placed wrong. It needs to be after path to libraries is set.

https://github.com/sympy/sympy-live/blob/4a860ce5dca1a5662783191eaf032c54461d08f2/appengine_config.py#L2-L6

I'll fix it in a bit.

**Comment by aktech** [comment] 2021-01-21 20:22
After this PR https://github.com/sympy/sympy-live/pull/182 is merged everything should work.

**Comment by Abhishek-IOT** [comment] 2021-01-22 03:29
@aktech  Yes same error was showing on wsl with traceback Fix pkg_resource import.

**Comment by Abhishek-IOT** [comment] 2021-01-22 03:35
@aktech Sir,I had also opened the PR #179 but that did'nt get merged can you help me that what I am going wrong in it,....
As added the documentation link on the line of log in because of the previous issue opened by me....then I updated the readme without hindering the repository but it did'nt get merged.

**Comment by Abhishek-IOT** [comment] 2021-01-24 15:09
@ivanistheone  How can I contribute if my development server is not working???..can I just update the files without running docker-compose up command??

**Closed** 2021-02-02 13:20 UTC
